@baseUrl = http://localhost:3000/api

@resourceName = categories

# @name getAllCategories
GET {{baseUrl}}/{{resourceName}}

###

# @name addNewCategory
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
  "name" : "Laptop"
}

###

# @name updateCategory
PATCH {{baseUrl}}/{{resourceName}}/2
Content-Type: application/json

{
  "name" : "new Laptop"
}

###

# @name removeCategory
DELETE {{baseUrl}}/{{resourceName}}/2
